name: stats_and_estates
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.9
  cupertino_icons: 1.0.6

  firebase_core: ^2.22.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.2
  provider: ^6.1.1

  gap: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.6
  flutter_switch: ^0.3.2
  full_screen_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Stats & Estates.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/property1/
    - assets/images/property2/
    - assets/images/property3/
    - assets/images/property4/
    - assets/images/property5/
    
  fonts: 
    - family: CDBlack
      fonts: 
        - asset: assets/fonts/CinzelDecorative-Black.ttf
    - family: CDBold
      fonts:
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
    - family: CDRegular
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
    - family: DMSansBold
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
    - family: DMSansMedium
      fonts:
        - asset: assets/fonts/DMSans-Medium.ttf
    - family: DMSansRegular
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
    - family: BabasNeueRegular
      fonts: 
        - asset: assets/fonts/BebasNeue-Regular.ttf
